name: Workflow for python app

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build new app
        run: |
          pwd
          ls -la
          docker build -t test_app:1.0.0 .
          docker images
