name: Workflow for python app

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildix
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 1994052294/homework:latest

      - name: Docker logout
        run: docker logout

      - name: Deployment
        env: 
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_USER: ${{ secrets.AWS_USER }}
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        run: | 
          echo "$AWS_PRIVATE_KEY" > /tmp/aws_private_key.pem
          chmod 400 /tmp/aws_private_key.pem

          ssh -o StrictHostKeychecking=no -i /tmp/aws_private_key.pem $AWS_USER@$AWS_HOST << EOF

          sudo docker rm -f py-app || true
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/homework:latest
          sudo docker run -d --name py-app -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/homework:latest
          EOF

      - name: Clean up
        run: rm /tmp/aws_private_key.pem
